# File with constants
# For reviewers: added by Students in S7

# URL is replaced with server URL generated by platform
URBAN_ROUTES_URL = 'https://cnt-c0d9a00c-9d24-4c13-bfb8-c31d2d0a6faa.containerhub.tripleten-services.com/'

TARIFFS = ('Business','Sleepy','Holiday','Talking','Supportive','Glossy')

ADDRESS_FROM = 'East 2nd Street, 601'
ADDRESS_TO = '1300 1st St'
PHONE_NUMBER = '+1 123 123 12 12'
CARD_NUMBER, CARD_CODE = '1234 5678 9100', '111'
MESSAGE_FOR_DRIVER = 'Stop at the juice bar, please'